### ISSUE TITLE
执行NewGlobalRefs报空指针错误

### ISSUE THREAD

**Issue by freemanZYQ** [zhkl0228/emulator#10]
你好，zhkl0228 ，我在调用so初始化时候，在执行newGlobalRefs 报空指针错误，能帮忙看看么
[17:12:54 108] DEBUG [cn.banny.emulator.linux.ARMSyscallHandler] (ARMSyscallHandler:433) - handleInterrupt intno=2, NR=-1073743908, svcNumber=0x106, PC=unicorn@0xfffe007c, syscall=null
java.lang.NullPointerException
	at cn.banny.emulator.linux.android.dvm.DalvikVM$7.handle(DalvikVM.java:112)
	at cn.banny.emulator.linux.ARMSyscallHandler.hook(ARMSyscallHandler.java:71)
	at unicorn.Unicorn.invokeInterruptCallbacks(Unicorn.java:123)
	at unicorn.Unicorn.emu_start(Native Method)
	at cn.banny.emulator.AbstractEmulator.emulate(AbstractEmulator.java:197)
	at cn.banny.emulator.AbstractEmulator.eFunc(AbstractEmulator.java:283)
	at cn.banny.emulator.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:191)
	at cn.banny.emulator.linux.LinuxModule.emulateFunction(LinuxModule.java:154)
	at cn.banny.emulator.linux.android.dvm.DvmClass.callStaticJniMethod(DvmClass.java:144)
	at com.xingin.xhs.Shield.<init>(Shield.java:73)
	at com.xingin.xhs.Shield.main(Shield.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

**Comment by freemanZYQ** [comment]
这是对应的so文件
[so.zip](https://github.com/zhkl0228/emulator/files/3169916/so.zip)

**Comment by zhkl0228** [comment]
com/xingin/shield/http/RedHttpInterceptor->getBytesOfParams(Lokhttp3/Request;)[B生成的数据发一份有效的给我
android/content/pm/Signature->toByteArray()[B
这个签名发个正确的给我，jni里面有校验

**Comment by zhkl0228** [comment]
最新提交的代码包含Shield测试用例，你试下能不能解决你的问题

**Comment by freemanZYQ** [comment]
测试数据如下，
"channel=Xiaomicursor_score=deviceId=e3480298-0835-355d-8972-bdce279963fcdevice_fingerprint=201905131833071ecc9d2a55804f47292bdd7406cf7ec201e39595e683d961device_fingerprint1=201905131833071ecc9d2a55804f47292bdd7406cf7ec201e39595e683d961geo=eyJsYXRpdHVkZSI6MC4wMDAwMDAsImxvbmdpdHVkZSI6MC4wMDAwMDB9
lang=ennote_index=0oid=homefeed_recommendplatform=androidrefresh_type=1sid=session.1557743689143267176190sign=03c10ccc41146a7728aa4ef604ac1bcdt=1557744164trace_id=9265ef6b-b869-3bd9-97c5-3214a93ff85durl=/api/sns/v6/homefeedversionName=5.44.0
".getBytes() ，hashCode=-1083242518 ,
我替换后，执行下来，
okhttp3/Request$Builder->header name=shield, value= 这里的值还是为空
正常情况下这里会生成一个shield的字符串

**Comment by zhkl0228** [comment]
为什么value为空的话，只能自己去逆向分析so逻辑了，有可能某个地方的判断满足不了

**Comment by freemanZYQ** [comment]
好，谢谢 ！

**Comment by jtduan** [comment]
小红书这个接口设计的很奇葩，app抓包实际上是有2个请求的，第一个请求带的shield确实是空，然后根据服务器返回的数据修正so中的参数，再请求带的shield才是正确的值

**Comment by freemanZYQ** [comment]
@jtduan   难怪，这个问题困扰了有段时间，能帮帮忙么

**Comment by jtduan** [comment]
把so里面7fdaf4a391818011这个字符串替换成小红书接口返回的16位字符串应该调用应该就有结果了
![image](https://user-images.githubusercontent.com/14127164/57667166-2786ca00-7635-11e9-84df-c2bd5d577a7f.png)

这是我之前替换过的so，签名验证已经去掉了
[libshield.so.zip](https://github.com/zhkl0228/unidbg/files/3175635/libshield.so.zip)
![image](https://user-images.githubusercontent.com/14127164/57667533-7c771000-7636-11e9-8dc8-effeaf7c801a.png)

**Comment by freemanZYQ** [comment]
@jtduan  谢谢，测试可以

**Comment by svengong** [comment]
> @jtduan 难怪，这个问题困扰了有段时间，能帮帮忙么

搞定了么，加个好友呀

**Comment by frank13810055034** [comment]
加个好友qq 43401269 或者微信wapsoap 交流下libshield.so

**Comment by hu-jinwen** [comment]
> 这是对应的so文件 还有对应的测试文件
> [so.zip](https://github.com/zhkl0228/emulator/files/3169916/so.zip)

有个不明白的地方想请教一下大佬！
```java
OkHttpClient mOkHttpClient = new OkHttpClient().newBuilder()
        .addInterceptor(new RedHttpInterceptor(emulator, module, vm, interceptor))
        .build();
```
`new RedHttpInterceptor(emulator, module, vm, interceptor)`应该没有这么奇怪的构造方法吧！
大佬你用的什么版本的xhs，能分享一下吗
